### ISSUE TITLE
Compatibility for 3rd party mods

### ISSUE THREAD

**Issue by IronworksProductions** [NillerMedDild/ModpackUploader#17]
### Modpack Version

0.0.1

### Describe your issue.

As mentioned in #16. The manifest.json created by modpackuploader is invalid for me. Curseforge is saying it references:
```
[The status of the file PhoenixRising 0.0.1 (Realms Of Creation Framework(Protocol Alpha)) has been changed to Rejected](https://www.curseforge.com/minecraft/modpacks/framework-prt-alpha/files/3793382)

Notes:
Invalid manifest.json file:
References file with invalid status: 3253803 (projectID 462460 - UnderReview), 3202390 (projectID 446346 - UnderReview).
If you have any questions please contact our support team https://support.curseforge.com/.
```
Looking those two projectIDs and file ids on cflookup tells me the two mods are: https://cflookup.com/462460?fileId=3253803  and https://cflookup.com/446346?fileId=3202390
There are 4 noncurseforgemods in the pack I am creating, computronics, a stellarsky bugfix, and a fork of malsiscore created by dockter. All 4 of these are authorized for distribution on curseforge via the allowed 3rd party mods list.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NielsPilgaard** [comment]
Thanks for the report. ModpackUploader simply reads your `minecraftinstance.json` and transforms what it finds to a `manifest.json` - These projects must be in your instance, something has likely gone wrong in the CurseForge Client.

**Comment by IronworksProductions** [comment]
That worked! If you don't mind me asking, how do I add a 3rd party mod to the settings file for moduploader. Computronics is being treated as a curseforge mod by moduploader it seems, even though its a 3rd party mod that has never been officially submitted to curseforge

**Comment by NielsPilgaard** [comment]
I.. totally forgot 3rd party mods existed, I'll have to add handling of those ^^'
At the moment they'll simply be ignored. I don't know why/how Computronics is being seen as a CurseForge mod, I just read the `minecraftinstance.json` 😅 it's in the for some reason

**Comment by IronworksProductions** [comment]
It looks like that is because someone was an idiot and attempted to submit it to curseforge, optifine somehow was in the minecraftinstance.json as well because of this same reason. Computronics file id leads to here: https://cflookup.com/446346?fileId=3202390 Optifines file id leads to here: https://cflookup.com/462460?fileId=3253803

<blockquote><img src="https://media.forgecdn.net/avatars/thumbnails/343/214/256/256/637488101185625226.jpeg" width="48" align="right"><div><strong><a href="https://www.curseforge.com/minecraft/mc-mods/cc-addons">ComputerCraft Addons</a></strong></div><div>ComputerCraft Addons</div></blockquote>
<blockquote><img src="https://media.forgecdn.net/avatars/thumbnails/360/813/256/256/637525437189448997.jpeg" width="48" align="right"><div><strong><a href="https://www.curseforge.com/minecraft/mc-mods/optifine-albehero">OPTIFINE ALBEHERO</a></strong></div><div>,</div></blockquote>
