### ISSUE TITLE
Modpacks with a space in the name break this format

### ISSUE THREAD

**Issue by SirOMGitsYOU** [NillerMedDild/ModpackUploader#18]
### Describe your issue.

If the Modpack name holds a space the URL input in the server-setup-config.yml is wrong i.e for my modpack all my versions are "_ABOE 3-v[VERSION]_", when Curseforge formats this into a URL they end up putting "_ABOE+3-v[VERSION]_" it's a small change but it's also nice to have consistency with it :)

**Comment by SirOMGitsYOU** [comment]
To summarise, a check for any whitespace in the CLIENT_ZIP_NAME function as to not replace all CLIENT_NAME whitespace, and replace it with a '+' to match up with how curseforge changes the filename.

**Comment by NielsPilgaard** [comment]
To be honest I think the best approach would be to not have whitespaces in file names :P

But sure, seems like an easy fix 👍

**Comment by NielsPilgaard** [comment]
There you go: https://github.com/EnigmaticaModpacks/ModpackUploader/releases/tag/2.2.1

<blockquote><img src="https://opengraph.githubassets.com/fbd0da313c65a2b099f0d8b55a88dddf24da4c6f13267f5a5943ab95f7383f64/EnigmaticaModpacks/ModpackUploader/releases/tag/2.2.1" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/EnigmaticaModpacks/ModpackUploader/releases/tag/2.2.1">Release 2.2.1 · EnigmaticaModpacks/ModpackUploader</a></strong></div><div>Fixed serverstarter config compat not working with modpack files with spaces in the name: #18
Full Changelog: 2.2.0...2.2.1</div></blockquote>
