### ISSUE TITLE
LICENSE would be better placed at the root of the repository

### ISSUE THREAD

**Issue by FederAndInk** [NillerMedDild/ModpackUploader#20]
### Describe your suggestion

I think the LICENSE file should be placed at the root of the repository, so everyone can see it better and Github too.

### Why would you like this added/changed?

For better visibility and github integration

**Comment by NielsPilgaard** [comment]
I thought it worked fine in `.github` 😅 thanks!

**Comment by FederAndInk** [comment]
No problem :+1:
