### ISSUE TITLE
[Linux] curl.exe doesn't exist

### ISSUE THREAD

**Issue by FederAndInk** [NillerMedDild/ModpackUploader#22]
### Modpack Version

none

### Describe your issue.

`curl.exe` won't work on Linux, I think you'll need a variable set to `curl.exe` on win and to `curl` on Linux

btw, I think you need to change your issue template for this repo ^^

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NielsPilgaard** [comment]
Thanks for the report, I'll get that fixed (eventually 😅)

**Comment by FederAndInk** [comment]
thanks,
I would have done it, but I don't know powershell, I've seen there is `$IsWindows` `$IsLinux` variables though.
Python could have been more widespread and Linux friendly :p

**Comment by FederAndInk** [comment]
> Python could have been more widespread and Linux friendly :p

But great project anyways :smile:

**Comment by NielsPilgaard** [comment]
I removed those variables 😓

**Comment by FederAndInk** [comment]
what do you mean?
shouldn't they be built-in?

**Comment by FederAndInk** [comment]
this is what I get out of the box:

```pwsh
PS /home/nihil> Write-Host $IsLinux
True
PS /home/nihil> Write-Host $IsWindows
False
PS /home/nihil> Write-Host $IsMacos
False
```

**Comment by NielsPilgaard** [comment]
I'm afraid those variables only exist in Powershell Core, not the windows native version, so I can't rely on them :/

**Comment by FederAndInk** [comment]
well then, you could try to see if the variable is defined and do:

```
if IsWindows not defined or $IsWindows
  use curl.exe
else
  use curl
```

**Comment by FederAndInk** [comment]
found this otherwise: https://devblogs.microsoft.com/scripting/powertip-determine-your-version-of-powershell-and-host-operating-system/

using `$PSVersionTable`

<blockquote><img src="https://devblogs.microsoft.com/scripting/wp-content/uploads/sites/29/2020/10/dr_scripto.jpg" width="48" align="right"><div><img src="https://devblogs.microsoft.com/scripting/wp-content/uploads/sites/29/2018/10/Microsoft-Favicon.png" height="14"> Scripting Blog</div><div><strong><a href="https://devblogs.microsoft.com/scripting/powertip-determine-your-version-of-powershell-and-host-operating-system/">PowerTip: Determine your version of PowerShell and host operating system</a></strong></div><div>Identify your PowerShell environment by making use of built-in PowerShell variables.</div></blockquote>

**Comment by NielsPilgaard** [comment]
Should be all fixed, thanks for the helpful pointers :)
Edit: Would you mind checking if the fix actually works? I only have a Windows laptop at my disposal

**Comment by FederAndInk** [comment]
no problem, thank you for the fix.
btw, isn't possible to store `curl` or `curl.exe` in a variable like in bash? and use it as a command

**Comment by NielsPilgaard** [comment]
Oh, it actually is. That simplifies this greatly.

**Comment by NielsPilgaard** [comment]
Changed, thanks :D https://github.com/EnigmaticaModpacks/ModpackUploader/releases/tag/2.3.2

<blockquote><img src="https://opengraph.githubassets.com/5b16d28e0c84a51ebb8ca5de167bcde169b21eedd1b055db0b51c33d965d2e90/EnigmaticaModpacks/ModpackUploader/releases/tag/2.3.2" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/EnigmaticaModpacks/ModpackUploader/releases/tag/2.3.2">Release 2.3.2 · EnigmaticaModpacks/ModpackUploader</a></strong></div><div>What's Changed

simplify how the curl command is determined by @NielsPilgaard in #26

Full Changelog: 2.3.0...2.3.2</div></blockquote>
