### ISSUE TITLE
[Linux] using ModListCreator module create a subdirectory `.\`

### ISSUE THREAD

**Issue by FederAndInk** [NillerMedDild/ModpackUploader#23]
### Modpack Version

none

### Describe your issue.

I think you need to replace the `\` directory separator by `/` it should work on windows too

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NielsPilgaard** [comment]
Thanks for the report, have you made this fix yourself and verified that it works? Cause then a PR would be super helpful :D
