### ISSUE TITLE
changelog/modlist jar can't be retrieved if not latest

### ISSUE THREAD

**Issue by FederAndInk** [NillerMedDild/ModpackUploader#29]
### Modpack Version

none

### Describe your issue.

This doesn't work:
https://github.com/EnigmaticaModpacks/ModpackUploader/blob/03ed0311fd8219921a3b9ee2a4dbea166cdf098d/modpack-uploader.ps1#L33
if this is not the latest file here:
https://github.com/EnigmaticaModpacks/ModpackUploader/blob/03ed0311fd8219921a3b9ee2a4dbea166cdf098d/settings.ps1#L75

(currently the latest is 4.0.2)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Thanks for the report, I'll look into how to fix it :)

**Comment by FederAndInk** [comment]
Here is what I can think of:
1. add a `CHANGELOG_GENERATOR_VERSION` variable and use it to construct the URL with the already provided filename `$CHANGELOG_GENERATOR_JAR`, and not relying on the github API
2. search the tags for the filename provided

I think 1. would be good enough and is what is generally used in like package script
