### ISSUE TITLE
Check for cf project status before adding mod to manifest

### ISSUE THREAD

**Issue by IronworksProductions** [NillerMedDild/ModpackUploader#31]
### Modpack Version

NA

### Describe your issue.

For a good while now, I have had to manually modify my instances.json to keep curseforge from rejecting the pack. This is due to the fact that two 3rd party mods were submitted to curseforge and are stuck in the changes required state. One of them is optifine which should never be distributed with the pack, and the other is computronics which is on the 3rd party mod list but due to someone deciding to submit it to curseforge directly, the instances grabs it and Modpackuploader throws it into the manifest without a second glance at it. Having spoken with the devs in the Curseforge Dev channel, they told me to suggest you check the cf project status before adding it to the manifest: 
![image](https://user-images.githubusercontent.com/7560033/206354168-919d459a-59f8-4584-979a-91d895536020.png)
![image](https://user-images.githubusercontent.com/7560033/206354341-6e2bf859-c92a-4bbb-8f1d-15ab3bd4e476.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Thanks for the report. I'm afraid I'm not willing to use the CurseForge API, I'm worried I'd somehow break the [Terms & Conditions](https://support.curseforge.com/en/support/solutions/articles/9000207405-curse-forge-3rd-party-api-terms-and-conditions) and face awful consequences 😅 

Also, this tool doesn't actually support third party mods at the moment, as you found in #17
