### ISSUE TITLE
[1.15.2] Deletes mods

### ISSUE THREAD

**Issue by TheUntamed** [NillerMedDild/ModpackUploader#8]
When I use this everything works just fine but also half my mods are deleted out of the mods folder of my instance. (The uploaded client and server file still containe all mods.)

**Comment by NielsPilgaard** [comment]
I cannot reproduce this, could you give me steps to reproduce it please?

**Comment by TheUntamed** [comment]
I downloaded the latest ModpackUploader Version unziped it and moved all files into my Modpack Instance folder.
It's a 1.15.2 modpack
The .build.json: https://pastebin.com/SiKKB2Nn
The settings.ps1: https://pastebin.com/mt22HBZZ

Then I just started the ModpackUploader.bat
A .zip for the client and one for the server were created, uploaded and also placed inside my Instance folder. They contained all mods.
From the mod folder of the Instance ~50% of the mods were removed. Tried this twice and the mods that were deleted were different mods both times.

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/SiKKB2Nn">{      "packAuthor": "MyName",      "minecraftVersion": "1.15.2",      "modLoade - Pastebin.com</a></strong></div></blockquote>
<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/mt22HBZZ"># Settings for the ModpackUploader  # For details/help see: https://github.com/N - Pastebin.com</a></strong></div></blockquote>

**Comment by NielsPilgaard** [comment]
Don't include "mods" in the `.build.json`, it does that on it's own :)

**Comment by NielsPilgaard** [comment]
Other than that, I don't know what could cause this, I'll have a look this evening if fixing the `.build.json` doesn't help.

**Comment by TheUntamed** [comment]
Should I also remove the "mods" from the Server Contents to zip in settings.ps1?

**Comment by NielsPilgaard** [comment]
Nope :)

**Comment by NielsPilgaard** [comment]
Any update on this issue?

**Comment by TheUntamed** [comment]
Not yet. Haven't got the time to test it again. Not sure if I will be able to today. Tomorrow for sure.

**Comment by TheUntamed** [comment]
Removing the "mods" folder from the .build.json did the thing I think. No mod files got removed this time

**Comment by NielsPilgaard** [comment]
Awesome :)

**Comment by NielsPilgaard** [comment]
I can't do anything about that I'm afraid, the TwitchExportBuilder repo is archieved, so I can't make a bug report.

**Comment by TheUntamed** [comment]
I just saw that the settings-linux.cfg is not in the generated server pack.
Maybe I just missed a setting for that.

**Comment by NielsPilgaard** [comment]
`$CONTENTS_TO_ZIP = @("mods", "config")` 
Everything you want in the server files go into that setting
